name: flutter_things
description: A set of things you miss in Flutter
version: 0.2.0

environment:
  sdk: ^3.6.2
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.1.1
  logger: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">= 5.0.0 < 6.0.0"
