name: flutter_things
description: A set of things for Flutter
version: 0.4.2
repository: https://github.com/innerwilds/flutter_things

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0
