name: flutter_things
description: A set of things for Flutter
version: 0.6.5
repository: https://github.com/innerwilds/flutter_things

environment:
  sdk: ^3.7.0
  flutter: ">=3.29.0"

dependencies:
  flutter:
    sdk: flutter
  device_info_plus: ^11.1.1
  dart_things: ^0.8.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  mockito: ^5.4.5
  very_good_analysis: ^7.0.0
